### ISSUE TITLE
怎么自建bucket

### ISSUE THREAD

**Issue by git-wanglei** [everyx/scoop-bucket#5]
你好，刚开始用scoop，能交流下怎么自建bucket吗？

**Comment by everyx** [comment]
建立一个 git 仓库，然后参照官方仓库的目录结构就可以啦，bucket 的 json 文件，官方也有文档，参照着写就可以了

**Comment by git-wanglei** [comment]
只要在git建立一个目录结构吗？目录内的文件呢？

**Comment by everyx** [comment]
就 bucket 目录有用，其他是方便你管理的一些文件，比如我这里的 bin 目录用来自动更新 bucket 中的 json 文件，而 script 目录则放一些安装时依赖的脚本

**Comment by git-wanglei** [comment]
好的，我clone下你的看看，谢谢
